"""Reusable button labels for reply keyboards and text handlers."""

BTN_VPN_REQUEST = "✅ Запросить VPN"
BTN_STATUS = "📄 Мой статус"
BTN_REISSUE = "🔄 Переустановить VPN"
BTN_HELP = "❓ Помощь"
BTN_TROUBLE = "🛠 Если не работает"
BTN_INSTALL = "🧩 Как установить"
BTN_MIKROTIK = "🔧 MikroTik"
BTN_AUDIT = "🧾 Журнал действий"
BTN_REQUESTS = "🧑‍💼 Заявки"
BTN_USERS = "👥 Пользователи"
BTN_SETTINGS = "⚙️ Настройки"
BTN_LOGIN = "🔐 Войти (PIN)"
